development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: stokwell
  password: rus280280
  database: chance-web


test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: stokwell
  password: rus280280
  database: chance-web


production:
  adapter: postgresql
  database: chance_international_production
  user: deploy
  password: rus280280
