default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: stokwell
  password: rus280280
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: chance-web


test:
  <<: *default
  database: chance-web

stanging:
  <<: *default
  database: chance_international
  user: deploy
  password: <%=ENV["DATABASE_PASSWORD"]%>

production:
  <<: *default
  database: chance_international_production
  user: deploy
  password: <%=ENV["DATABASE_PASSWORD"]%>
