development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: chance-web
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: chance-web-test
  port: 5432


production:
  adapter: postgresql
  database: chance_international_production
  user: deploy
  password: rus280280
